from typing import Any

from fastapi import HTTPException, status

from app.providers.base import BaseProvider
from app.schemas.common import ProviderConfig


class StubProvider(BaseProvider):

    async def check(self) -> dict[str, Any]:
        return {"available": True, "latency_ms": 1, "error": None}

    async def generate_skeleton(self, prompt_data: dict[str, Any]) -> dict[str, Any]:
        return {
            "nodes": [
                {
                    "tempId": "node_1",
                    "title": "Инициализация проекта",
                    "description": "Создание репозитория и базовой структуры",
                    "category": "DEVOPS",
                    "estimatedHours": 2.0,
                },
                {
                    "tempId": "node_2",
                    "title": "Настройка зависимостей",
                    "description": "Установка ключевых библиотек",
                    "category": "BACKEND",
                    "estimatedHours": 3.0,
                },
            ],
            "edges": [
                {"sourceTempId": "node_1", "targetTempId": "node_2"},
            ],
            "totalEstimatedHours": 5.0,
            "modelUsed": "stub",
            "provider": self.config.provider,
        }

    async def enrich_task(self, prompt_data: dict[str, Any]) -> dict[str, Any]:
        return {
            "taskId": prompt_data.get("task", {}).get("taskId"),
            "checklist": ["Шаг 1", "Шаг 2"],
            "pitfalls": ["Подводный камень 1"],
            "links": [],
            "rawMarkdown": "# Markdown черновик",
            "wikiDraft": "# Wiki драфт",
            "modelUsed": "stub",
            "provider": self.config.provider,
        }

    async def mutate_graph(self, prompt_data: dict[str, Any]) -> dict[str, Any]:
        return {
            "patch": {
                "newNodes": [],
                "newEdges": [],
                "recalculatedTotalHours": None,
                "reasoning": "Stub reasoning",
            },
            "modelUsed": "stub",
            "provider": self.config.provider,
        }

    async def smart_recovery(self, prompt_data: dict[str, Any]) -> dict[str, Any]:
        return {
            "fixedPatch": {
                "newNodes": [],
                "newEdges": [],
                "recalculatedTotalHours": None,
                "reasoning": "Stub recovery",
            },
            "recoveryNote": "Stub recovery note",
            "modelUsed": "stub",
            "provider": self.config.provider,
        }

    async def generate_diagrams(self, prompt_data: dict[str, Any]) -> dict[str, Any]:
        return {
            "c4Code": "graph LR\n    A[Client] --> B[API]",
            "sequenceCode": "sequenceDiagram\n    A->>B: request",
            "classCode": "classDiagram\n    class A",
            "modelUsed": "stub",
            "provider": self.config.provider,
        }

    async def generate_wiki(self, prompt_data: dict[str, Any]) -> dict[str, Any]:
        return {
            "title": prompt_data.get("task", {}).get("taskTitle", "Wiki page"),
            "content": "# Wiki content\n\nGenerated by stub provider.",
            "modelUsed": "stub",
            "provider": self.config.provider,
        }


def get_provider(config: ProviderConfig) -> BaseProvider:
    if config.provider != "ollama" and not config.api_key:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"API key is required for provider '{config.provider}'",
        )
    return StubProvider(config)
